name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest
          # Optional linters/formatters:
          # pip install flake8 black

      - name: Run tests
        run: pytest -q
        # If your tests need env vars, add them here:
        # env:
        #   FLASK_ENV: testing
        #   DATABASE_URL: ${{ secrets.DATABASE_URL }}
